[tool.poetry]
name = "face-neural-network"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "face_neural_network"}]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.12.0"
torchvision = "^0.14.0"
fire = "^0.4.0"
tqdm = "^4.64.1"
matplotlib = "^3.6.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
