dataset:
  directory: cropped
  download:
    url: https://facesyntheticspubwedata.blob.core.windows.net/iccv-2021/dataset_1000.zip
    file: dataset_1000
  transform:
    seed: 42
    crop: 320
    resize: 256
  split:
    seed: 42
    test: 0.1

training:
  epochs: 3
  batch_size: 32
  landmarks:
    pool_size: 4
  optimizer:
    lr: 1e-3
