dataset:
  directory: cropped
  download:
    url: https://facesyntheticspubwedata.blob.core.windows.net/iccv-2021/dataset_100000.zip
    file: dataset_100000
  transform:
    seed: 42
    crop:
      min: 256
      max: 320
    resize: 256
  test:
    name: test
    seed: 42
    split: 0.1

training:
  epochs: 50
  batch_size: 32
  grad_batches: 2
  model:
    type: loose
    backbone:
      name: resnet34
      weights: IMAGENET1K_V1
    params:
      pool_size: 2
      levels: 1
      hidden_channels: 1024
  optimizer:
    learning_rate: 2e-4
    weight_decay: 1e-3
    mse_weight: 1.0
    bce_weight: 1.0
  test_dataset:
    directory: test

fine_tunning:
  epochs: 256
  batch_size: 32
  grad_batches: 2
  freeze_backbone: 1
  optimizer:
    learning_rate: 1e-5
    weight_decay: 1e-3
    mse_weight: 1.0
    bce_weight: 1.0
  train_dataset:
    directory: ibugmask/train
  test_dataset:
    directory:  ibugmask/test

label_adaptation:
  epochs: 256
  batch_size: 32
  grad_batches: 2
  train_dataset:
    directory: ibugmask/train
  test_dataset:
    directory: ibugmask/test
  optimizer:
    learning_rate: 2e-4
    weight_decay: 1e-3


