dataset:
  directory: cropped
  download:
    url: https://facesyntheticspubwedata.blob.core.windows.net/iccv-2021/dataset_100000.zip
    file: dataset_100000
  transform:
    seed: 42
    crop:
      min: 300
      max: 320
    resize: 256
  test:
    name: test
    seed: 42
    split: 0.1

training:
  epochs: 20
  batch_size: 32
  grad_batches: 4
  model:
    backbone:
      name: resnet34
      weights: IMAGENET1K_V1
      params:
        pool_size: 2
        levels: 2
        hidden_layers: 1024
  optimizer:
    learning_rate: 2e-4
    weight_decay: 1e-6
